# Generated by Django 5.2.1 on 2025-06-02 05:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("merging", "Merging"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("downloaded_size", models.BigIntegerField(default=0)),
                ("speed", models.CharField(blank=True, max_length=50)),
                ("eta", models.CharField(blank=True, max_length=50)),
                ("total_segments", models.IntegerField(default=0)),
                ("downloaded_segments", models.IntegerField(default=0)),
                ("failed_segments", models.IntegerField(default=0)),
                ("output_path", models.CharField(blank=True, max_length=1000)),
                ("temp_dir", models.CharField(blank=True, max_length=1000)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("encryption_key", models.TextField(blank=True)),
                ("encryption_iv", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DownloadSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("url", models.URLField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="downloader.downloadtask",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "unique_together": {("task", "index")},
            },
        ),
    ]
