# Generated by Django 5.2.1 on 2025-06-02 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("module", models.CharField(blank=True, max_length=100)),
                ("function", models.CharField(blank=True, max_length=100)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("download_started", "Download Started"),
                            ("download_completed", "Download Completed"),
                            ("download_failed", "Download Failed"),
                            ("download_paused", "Download Paused"),
                            ("download_resumed", "Download Resumed"),
                            ("download_cancelled", "Download Cancelled"),
                            ("file_deleted", "File Deleted"),
                            ("file_moved", "File Moved"),
                            ("merge_started", "Merge Started"),
                            ("merge_completed", "Merge Completed"),
                            ("merge_failed", "Merge Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
